#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "./stack.h"
#include "./linkedlist.h"
#include "./i_o_process.h"
#include "./basic_controls.h"
#include "./version_manage.h"